# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffcfb9c16f68894fa5e88b4a36f38a8a670f6c725bcb144dae44c9f8df22bf231993e09074e4eb6d803035018b92a50f3b9e8587ded916407cddc16bade3f8a2

test:
  secret_key_base: a6e15053237f8c14be0d374a44454359ab1ae2ed98c143150823673fb75bb74c06a4e361a79aaf0ed018f82612f5547b707f8c5ee7cd4c8959a0c15adcf83119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
